services:
  registry:
    image: registry:2
    container_name: registry
    ports:
      - "5001:5000" 
    volumes:
      - registry_data:/var/lib/registry  

  registry-ui:
    image: joxit/docker-registry-ui:1.5-static
    container_name: registry-ui
    ports:
      - "8082:80"  
    environment:
      - REGISTRY_TITLE=SUPMIT Registry  
      - REGISTRY_URL=http://registry:5000  
    depends_on:
      - registry  

volumes:
  registry_data:  